### ISSUE TITLE
Landscape，Select an Existing application，the data source that applies the drop-down box needs to be adjusted

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.PM#109]
“选择已有应用”弹窗，应用下拉框应过滤当前项目已存在的应用；

即应用下拉框的应用应满足以下条件：
1. 属于当前项目关联的环境/集群；
2. 不属于当前项目；
3. 未删除；

![image](https://user-images.githubusercontent.com/95004531/173297780-5d102287-7919-40cb-96ce-0e96ae0abd9d.png)

**Comment by codding-y** [comment]
产品确认是选择全部的应用。

**Comment by LazyEar0** [comment]
无“选择已有应用”功能
