### ISSUE TITLE
Landscape，After an associated application is edited, the application disappears

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.PM#113]
操作步骤：
1.A项目 - 选择已有应用，成功关联B项目的应用 “application01”；
2.A项目下，编辑应用 “application01”，保存成功后，查看B项目下的应用；
3.B项目下，编辑应用 “application01” ， 保存成功后，查看A 项目下的应用；

实际结果：
步骤2：B项目下，应用 “application01” 消失；
步骤3：A项目下，应用 “application01” 消失；

预期结果：
编辑应用保存后，应用不消失，并更新修改的数据；

![image](https://user-images.githubusercontent.com/95004531/173308146-743283e6-de82-4555-ba6a-42aac4fe88ce.png)

**Comment by codding-y** [comment]
No recurrence

**Comment by LazyEar0** [comment]
resolved
