### ISSUE TITLE
panorama- translate

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.PM#13]
![image](https://user-images.githubusercontent.com/102500164/160371323-72f99a58-35ec-47bc-945f-0fa663c2db0d.png)

操作步骤：中英文翻译
预期结果：点击翻译中文翻译成功
实际结果：未翻译成功

**Comment by codding-y** [comment]
Left navigation data from authsystems.
And i think the data entered by the user should not add i18n

**Comment by LazyEar0** [comment]
后期接入全局导航，菜单i18n功能由全局导航提供，此问题暂时关闭。
