### ISSUE TITLE
Team . Determine whether an application exists when deleting an project

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.PM#147]
团队菜单下，删除项目时，应判断该项目下是否存在应用，如存在应用，则不可删除
![image](https://user-images.githubusercontent.com/95004531/179710302-b5997bea-c3a3-43e8-8bcf-7f78c481983a.png)

**Comment by LazyEar0** [comment]
原始需求：仅团队菜单下删除项目，会判断此逻辑；在全景菜单下，删除项目，不需要判断此逻辑，直接删除；
实际结果：团队菜单和全景菜单下，删除项目，都判断了是否存在应用，需要根据需求调整。

**Comment by LazyEar0** [comment]
原始需求：仅团队菜单下删除项目，会判断此逻辑；在全景菜单下，删除项目，不需要判断此逻辑，直接删除；
实际结果：团队菜单和全景菜单下，删除项目，都判断了是否存在应用，需要根据需求调整。

**Comment by xie1wei2** [comment]
全景模式下，删除项目保持与团队一致，先删除项目下对应内容。避免误删除。

**Comment by LazyEar0** [comment]
需求变更
