### ISSUE TITLE
Project . When editing a project, the cluster associated with an application cannot be unselected

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.PM#151]
编辑项目时，不可取消选中 被该项目下应用所关联的 环境集群
![image](https://user-images.githubusercontent.com/95004531/179715128-8e42c7c4-4a37-4a54-a014-f7fc9be2c091.png)

**Comment by codding-y** [comment]
和产品讨论过，可以 @xie1wei2

**Comment by LazyEar0** [comment]
因有需求，项目的环境集群>该项目中应用的环境集群，故当项目中的应用已关联某环境/集群，编辑项目时，不可取消选中该集群
