### ISSUE TITLE
Team . Missing default values for the project team

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.PM#165]
团队菜单下，新增项目，所属项目团队应默认选中当前所在团队，可修改

![image](https://user-images.githubusercontent.com/95004531/181412900-6f783832-a2e7-4700-98c9-9c842f376814.png)

**Comment by codding-y** [comment]
需求变动：默认选中该团队，但是不可修改。

**Comment by LazyEar0** [comment]
resolved
