### ISSUE TITLE
Landspace . The position changes after the drop-down box is selected

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.PM#188]
下拉框选中内容后，位置发生变化

https://user-images.githubusercontent.com/95004531/186829973-55ded5e2-d4b8-48a2-a9be-17e8625c5e5b.mp4

**Comment by codding-y** [comment]
@capdiem

**Comment by capdiem** [comment]
@LazyEar0 很久之前的问题，已经复现不了了？
