### ISSUE TITLE
panorama-search buttoninvalid

### ISSUE THREAD

**Issue by wangwenbo33** [masastack/MASA.PM#19]
![image](https://user-images.githubusercontent.com/102500164/160983496-43334fa0-f28a-4df1-94bf-952a0e3ff22f.png)
![image](https://user-images.githubusercontent.com/102500164/160983542-f98d3c8f-4231-4647-9614-baadba87c5a4.png)
操作步骤：点击搜索框点击搜索点击回车无法搜索
预期结果：搜索成功
实际结果：搜索失败

**Comment by LazyEar0** [comment]
resolved
