### ISSUE TITLE
Global . The drop - down box should self-adjust back to the top

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.PM#195]
打开下拉框，滑动至底部，关闭下拉框，再次打开时，应回到顶部，现仍在底部
![image](https://user-images.githubusercontent.com/95004531/187151324-0a9b0743-4d9a-48dc-a0d9-8d9539e07b64.png)

**Comment by capdiem** [comment]
@LazyEar0 我不觉得这是BUG，组件行为就是如此，Vuetify也是如此

**Comment by LazyEar0** [comment]
@xie1wei2   请确认下拉框行为：窗口内将下拉框的滚动条滑动至底部，关闭窗口。再次打开窗口，打开下拉框，滚动条是否需要回到顶部

**Comment by masastack-opensource** [comment]
在另一个项目重构
