### ISSUE TITLE
Team . Deleted items are still displayed in the team

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.PM#196]
全景菜单下删除环境的项目，进入团队菜单，仍显示
![image](https://user-images.githubusercontent.com/95004531/187170824-5d1cd2cf-6ceb-4dbb-8d62-74d49756e4f4.png)

**Comment by codding-y** [comment]
未复现

**Comment by LazyEar0** [comment]
当项目/应用所关联的环境/集群被删除，该项目如何处理？

**Comment by LazyEar0** [comment]
逐级删除，删除项目时判断项目下是否有应用，删除集群时，判断集群下是否有项目，删除环境时，判断环境下是否有集群。

**Comment by LazyEar0** [comment]
删除集群时，应判断是否存在项目，存在项目的集群不能删除

**Comment by LazyEar0** [comment]
resolved
