### ISSUE TITLE
MASA.PM Roadmap for 0.70

### ISSUE THREAD

**Issue by codding-y** [masastack/MASA.PM#204]
### Roadmap

This issue represents a list of major investments that our team will focus on in the 0.7.0 time frame. It doesn't include all the features and bug fixes we'll be working on in the meantime
这个Issue代表我们团队将在 0.7.0 内重点关注的列表。它不包括我们将在此期间进行的所有功能和错误修复。

Note that this is an aspirational list of what we hope to get to. Many of these items will require thorough investigation and design, which can result in changes to our plans. We will end up cutting some things and making changes as we go, but will try to keep this issue up to date to reflect on our progress and learnings.
请注意，这是一个我们希望达到的愿望清单。 其中许多项目需要彻底的调查和设计，这可能会导致我们的计划发生变化。我们最终可能会消减一些东西，并做出改变，但将努力保持这个Issue是最新的，以反映我们的进步和学习。  

The roadmap consists of the following features:
路线图包括以下特性

### Initialization（初始化）

* [x] 初始化环境 

  Initialize environment

* [x] 初始化集群

  Initialize cluster

* [x] 初始化种子数据（项目和应用）

  Initialize seed data (project and application)

### Overview（全景）

> 全景页环境、集群、项目、应用联动交互
>
> Overview page environment, cluster, project and application interaction

**Environment（环境）**

* [x] Add（新增）
* [x] Edit（编辑）
* [x] Delete（删除）
* [x] List（列表）
* [x] Detail（列表）

**Cluster（集群）**

* [x] Add（新增）
* [x] Edit（编辑）
* [x] Delete（删除）
* [x] List（列表）
* [x] Detail（列表）

**Project（项目）**

* [x] Add（新增）
* [x] Edit（编辑）
* [x] Delete（删除）
* [x] List（列表）
* [x] Detail（列表）

**App（应用）**

* [x] Add（新增）
* [x] Edit（编辑）
* [x] Delete（删除）
* [x] List（列表）
* [x] Detail（列表）

### Team（团队）

> 以团队视角查看项目和应用，以项目和应用为主体
>
> View projects and applications from a team perspective, focusing on projects and applications

**团队**

- [x] Detail（详情）

**Project（项目）**

* [x] Add（新增）
* [x] Edit（编辑）
* [x] Delete（删除）
* [x] List（列表）
* [x] Detail（列表）
* [x] Search（搜索）

**App（应用）**

* [x] Add（新增）
* [x] Edit（编辑）
* [x] Delete（删除）
* [x] List（列表）
* [x] Detail（列表）
* [x] Search（搜索）

**Comment by masastack-opensource** [comment]
在另一个项目重构
