### ISSUE TITLE
 team- head portrait

### ISSUE THREAD

**Issue by wangwenbo33** [masastack/MASA.PM#22]
![image](https://user-images.githubusercontent.com/102500164/160988001-607c1036-8bf3-4b16-9148-0a6bf7e8b1d3.png)
操作步骤：点击团队未显示管理员，成员头像以及名字
预期结果：显示管理员成员头像以及名字
实际结果：未显示管理员成员头像以及名字

**Comment by LazyEar0** [comment]
resolved
