### ISSUE TITLE
colony- clickcolony001 invalid

### ISSUE THREAD

**Issue by wangwenbo33** [masastack/MASA.PM#25]
![image](https://user-images.githubusercontent.com/102500164/160992911-f0b948bf-c2d0-40e6-98ec-155d6bf7cc44.png)
操作步骤：点击集群无法点击无编辑按钮
预期结果：正常点击显示编辑按钮
实际结果：点击集群无法点击无编辑按钮

**Comment by LazyEar0** [comment]
resolved
