### ISSUE TITLE
An error occurred when deleting an environment or cluster when creating or editing a project

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.PM#251]
新建/编辑项目时，删除环境/集群报错
![image](https://user-images.githubusercontent.com/95004531/210926783-04afe8b7-8051-4932-85e5-59fda813a09d.png)

**Comment by codding-y** [comment]
AutoComplete组件有问题，目前先替换为Select组件解决了此bug，少了搜索功能。等待组件修复在换回AutoComplete组件
