### ISSUE TITLE
project -newly increaseddemand  discrepancy

### ISSUE THREAD

**Issue by wangwenbo33** [masastack/MASA.PM#26]
![image](https://user-images.githubusercontent.com/102500164/160997570-a7fbc7c7-23b5-4e62-b6ff-403f2da570ba.png)
![image](https://user-images.githubusercontent.com/102500164/161189281-3cb8cd29-777e-4a22-b7c4-02c3c5778bec.png)

操作步骤：点击新增应用与设计图不符
预期结果：与设计一致
实际结果：与设计不一致

**Comment by LazyEar0** [comment]
待UI重新设计后，统一调整样式，此问题暂时关闭
