### ISSUE TITLE
Create a new APP, select the service type, and the window is closed

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.PM#266]
新建APP，选择服务类型，窗口 被关闭。
![image](https://user-images.githubusercontent.com/95004531/217417060-fd2e7a21-d018-4d0b-b7c9-5438e615133e.png)

**Comment by xyfy** [comment]
#269 with updated the componet package, this bug could not reproduce.

**Comment by xie1wei2** [comment]
新增APP应该可以选择类型

**Comment by xyfy** [comment]
> 

啥意思？现在不能吗？

**Comment by xyfy** [comment]
> 新增APP应该可以选择类型

啥意思？现在不能吗？
