### ISSUE TITLE
Click the new APP button twice before it takes effect

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.PM#267]
点击新建APP按钮，打开新建APP窗口，关闭窗口，再次点击新建APP按钮，第一次点击不生效，再次点击才打开新建APP窗口(点击应用卡片也存在此问题)
![image](https://user-images.githubusercontent.com/95004531/217697967-479313dc-f861-47a8-b852-9ee8e27124b8.png)

**Comment by zyz** [comment]
#271
