### ISSUE TITLE
in English, edit time "in" should be followed by a space, and the time interval should be separated

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.PM#268]
英文状态下，编辑时间 “in”后面应加空格，与时间间隔开
![image](https://user-images.githubusercontent.com/95004531/217737498-6e094ebe-83ec-4946-a0b3-fb394c2a338f.png)
![image](https://user-images.githubusercontent.com/95004531/217737696-b5fc5966-9bb0-4703-a22e-ece97fc556b8.png)

**Comment by zyz** [comment]
#275 Fix: in English, edit time "in" should be followed by a space
