### ISSUE TITLE
project- compileproject

### ISSUE THREAD

**Issue by wangwenbo33** [masastack/MASA.PM#27]
![image](https://user-images.githubusercontent.com/102500164/160998956-a4fe92c6-b51c-4b5e-8eeb-66b89f66a50b.png)
操作步骤：点击编辑项目，删除按钮有误差
预期结果：删除按钮应显示，删除项目
实际结果：删除按钮，只显示删除不显示项目

**Comment by LazyEar0** [comment]
删除功能的文案统一为“删除”，此问题不存在
