### ISSUE TITLE
Environment list height error

### ISSUE THREAD

**Issue by codding-y** [masastack/MASA.PM#283]
环境列表高度错误
![image](https://user-images.githubusercontent.com/42963214/222642831-47b106b5-8d80-4395-ba02-5b77c76674aa.png)

**Comment by zyz** [comment]
#299 The height of the environment list item is 48px

**Comment by LazyEar0** [comment]
![image](https://user-images.githubusercontent.com/95004531/235077943-7a3cc99c-c65a-4c47-91f3-88b6056017f4.png)

**Comment by zyz** [comment]
#379 The Environment list item interior height is set to 48px
