### ISSUE TITLE
Logo error

### ISSUE THREAD

**Issue by codding-y** [masastack/MASA.PM#285]
logo 替换成新的
![image](https://user-images.githubusercontent.com/42963214/222643938-23823c35-de65-4a64-b950-b54b369a5139.png)

**Comment by xyfy** [comment]
代码里看了，这个实际是使用的cdn里的图标

https://cdn.masastack.com/stack/images/logo/MASAStack/logo16_16.png

https://cdn.masastack.com/stack/images/logo/MASAStack/logo.png

@codding-y  这个如何替换？
