### ISSUE TITLE
Wrong background color when hovering

### ISSUE THREAD

**Issue by codding-y** [masastack/MASA.PM#286]
鼠标悬浮时背景颜色错误
![image](https://user-images.githubusercontent.com/42963214/222644168-98998e60-5846-401a-b29d-43edf6c3e348.png)

**Comment by zyz** [comment]
#299 Environment list item hover background color is #F6F8FD

**Comment by LazyEar0** [comment]
此问题仍存在

**Comment by zyz** [comment]
The background color code in the code is #F6F8FD
![图片](https://user-images.githubusercontent.com/714535/236129052-e0cc4375-07c7-4a1c-9483-7a1125b01385.png)

**Comment by limei7** [comment]
渲染出来， 颜色还是有点差别

**Comment by masastack-opensource** [comment]
在另一个项目重构
