### ISSUE TITLE
Team page app card spacing error

### ISSUE THREAD

**Issue by codding-y** [masastack/MASA.PM#287]
团队页面应用卡片的间距不对，应该为16px
![image](https://user-images.githubusercontent.com/42963214/222647158-1e5e044c-76f8-4d58-a834-3b6f617a5604.png)

![image](https://user-images.githubusercontent.com/42963214/222647316-65c46066-5ead-4773-8244-313b9714072d.png)

**Comment by zyz** [comment]
#305 Spacing is 16px
