### ISSUE TITLE
App card chip style error

### ISSUE THREAD

**Issue by codding-y** [masastack/MASA.PM#290]
应用卡片的环境集群标签样式不对
错误的： 
![image](https://user-images.githubusercontent.com/42963214/222654515-e5a5a1ca-8e3b-49e4-83f6-dd7d38076ce1.png)
UI设计：
![image](https://user-images.githubusercontent.com/42963214/222654313-00b9e503-55d9-43e1-b296-ac0eff5cdd2b.png)

**Comment by LazyEar0** [comment]
Card中 的标签边框不需要根据环境的颜色变化
![image](https://user-images.githubusercontent.com/95004531/236105361-bcb6d120-9bac-4b63-b43d-d6fe26b996ad.png)

**Comment by limei7** [comment]
![Uploading image.png…]()
