### ISSUE TITLE
project-creatordemand discrepancy

### ISSUE THREAD

**Issue by wangwenbo33** [masastack/MASA.PM#30]
![image](https://user-images.githubusercontent.com/102500164/161001509-0d446218-bcba-457a-8c19-845c32f8186f.png)
操作步骤：创建人未显示出来以及参与团队头像没显示出来
预期结果：显示创建人以及参与团队头像
实际结果：没有显示

**Comment by LazyEar0** [comment]
没有创建人
![image](https://user-images.githubusercontent.com/95004531/181194667-86e2defc-5e97-4362-b5c5-f5224d356c7e.png)

**Comment by LazyEar0** [comment]
resolved
