### ISSUE TITLE
In project details, the environment cluster is blank

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.PM#301]
团队-进入项目详情，编辑项目，删除已有的环境/集群，页面提示环境/集群必填，关闭弹窗。
![image](https://user-images.githubusercontent.com/95004531/223899095-c51f8207-60fc-4a78-bac6-289ce9e57723.png)
![image](https://user-images.githubusercontent.com/95004531/223899127-391c9490-b6fc-4d89-aaaf-3a5c0c3038a4.png)
项目详情中，环境/集群显示空白。
![image](https://user-images.githubusercontent.com/95004531/223899209-cec67d5e-6365-49d5-9927-9fd90da1391b.png)

**Comment by yanzhangpeng** [comment]
already repair
