### ISSUE TITLE
put into use-selectExisting application

### ISSUE THREAD

**Issue by wangwenbo33** [masastack/MASA.PM#31]
![image](https://user-images.githubusercontent.com/102500164/161003572-35dcdfcd-d6f3-4232-95c4-f4acd00ff3c5.png)
![image](https://user-images.githubusercontent.com/102500164/161191856-f5509258-cf0d-464f-8f3b-3a091702194e.png)
操作步骤：点击项目，选择添加选择已有应用与设计不一致
预期结果：与设计图一致
实际结果：与设计图不一致

**Comment by LazyEar0** [comment]
待UI重新设计后，统一调整样式，此问题暂时关闭
