### ISSUE TITLE
Description The row spacing is too small because the environment or cluster is associated

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.PM#319]
关联环境/集群，行间距过小
![image](https://user-images.githubusercontent.com/95004531/227092173-aae329a3-fc2a-48a7-b214-209e79b25237.png)
![image](https://user-images.githubusercontent.com/95004531/227092936-0015e8c4-95c8-4313-9872-f586cd529fbc.png)

**Comment by xyfy** [comment]
dump with https://github.com/masastack/MASA.PM/issues/326

**Comment by LazyEar0** [comment]
重复issue
