### ISSUE TITLE
colony-redactcolonyerror

### ISSUE THREAD

**Issue by wangwenbo33** [masastack/MASA.PM#33]
![image](https://user-images.githubusercontent.com/102500164/161007624-514d3eed-ca9b-45fd-a6f3-008e67a62b37.png)
操作步骤：点击编辑集群删除按钮
预期结果：删除按钮应是删除集群
实际结果：只有删除

**Comment by LazyEar0** [comment]
删除的文案统一“删除”，此问题不存在
