### ISSUE TITLE
circumstances-redactcircumstancesmistake

### ISSUE THREAD

**Issue by wangwenbo33** [masastack/MASA.PM#35]
![image](https://user-images.githubusercontent.com/102500164/161009763-1cab1b14-8079-4972-b09f-cabddc05f746.png)
操作步骤：点击编辑环境删除按钮
预期结果：删除按钮应显示删除环境
实际结果：删除按钮显示删除

**Comment by LazyEar0** [comment]
删除功能的文案统一为“删除”，此问题不存在
