### ISSUE TITLE
team-- compile projectword limit

### ISSUE THREAD

**Issue by wangwenbo33** [masastack/MASA.PM#37]
![image](https://user-images.githubusercontent.com/102500164/161174214-45c0b159-9ee2-42ef-98f4-5fb81d4aabf2.png)
操作步骤：点击编辑项目，项目名称字数限制显示2-100
预期结果：项目名称字数限制应是2-50
实际结果：实际显示字数2-100

**Comment by LazyEar0** [comment]
resolved
