### ISSUE TITLE
In the English state, the button for the delete operation is identified as "DELETE".

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.PM#375]
在英文状态下，删除操作的按钮标识为“delete”。（DCC自查后一并修改）
![image](https://user-images.githubusercontent.com/95004531/236105889-68384adf-5451-4e50-a087-371b56bdb9df.png)

**Comment by zyz** [comment]
https://github.com/masastack/MASA.Stack.Components/pull/611
