### ISSUE TITLE
In English writing, it is necessary to add spaces between words.

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.PM#376]
英文状态下，单词之间需要加空格（DCC自查后一并修改）
![image](https://user-images.githubusercontent.com/95004531/236106488-a3c7f6e3-c06c-4e4a-a886-23a419964dd6.png)
![image](https://user-images.githubusercontent.com/95004531/236106611-5e771edc-3c2d-4b17-af87-67c2c9098046.png)
![image](https://user-images.githubusercontent.com/95004531/236106965-9d8e1619-aecc-4ba4-bf7a-4c0b1b559b05.png)
![image](https://user-images.githubusercontent.com/95004531/236107000-24f0c91a-7bd3-49c9-9485-96787cd76715.png)
![image](https://user-images.githubusercontent.com/95004531/236107033-e6e1e0ec-4ff1-4fa3-bcfa-50257f6444fa.png)

**Comment by zyz** [comment]
#381
