### ISSUE TITLE
 colony--colonycompileword limit 

### ISSUE THREAD

**Issue by wangwenbo33** [masastack/MASA.PM#38]
![image](https://user-images.githubusercontent.com/102500164/161176089-5f351a9b-ccc5-4cfb-9ee4-f37a9726b2c9.png)
操作步骤：点击编辑集群集群名称字数限制显示2-100
预期结果：集群名称字数限制应是2-50
实际结果：字数限制是在2-100

**Comment by LazyEar0** [comment]
resolved
