### ISSUE TITLE
Editing the project will lose the application, editing the application has no problem

### ISSUE THREAD

**Issue by limei7** [masastack/MASA.PM#397]
![image](https://github.com/masastack/MASA.PM/assets/93168234/179fff55-a395-4428-a588-637af756821c)

**Comment by MayueCif** [comment]
编辑项目时，新增加集群环境，没有为应用添加集群环境。 @codding-y

**Comment by codding-y** [comment]
> 编辑项目时，新增加集群环境，没有为应用添加集群环境。 @codding-y

by design

**Comment by limei7** [comment]
iot-dev， test.masastack均未复现， 先关闭
