### ISSUE TITLE
【有概率】在项目团队页idle一段时间，刷新浏览器后，有概率出现当前团队被切换到其他团队的情况

### ISSUE THREAD

**Issue by limei7** [masastack/MASA.PM#405]
![image](https://github.com/masastack/MASA.PM/assets/93168234/ffa2550e-2156-491a-ad20-9de07a04e793)
上午有遇到两次
![image](https://github.com/masastack/MASA.PM/assets/93168234/4cb19c3a-c82f-412f-8c95-d683dec2ec2e)

**Comment by masastack-opensource** [comment]
在另一个项目重构
