### ISSUE TITLE
【有概率】团队成员登录PM后，当用户只有一个团队时，默认的选中的团队不能为空

### ISSUE THREAD

**Issue by limei7** [masastack/MASA.PM#409]
![image](https://github.com/masastack/MASA.PM/assets/93168234/5a0efca6-dbd7-4956-8092-fc3a45441c87)
我属于熬夜天团 ；用我的域账号登录进来之后， 默认是空； 应该默认是他旗下的这个团队， 因为他只有一个团队啊

**Comment by masastack-opensource** [comment]
在另一个项目重构
