### ISSUE TITLE
 new project-- submit

### ISSUE THREAD

**Issue by wangwenbo33** [masastack/MASA.PM#43]
![image](https://user-images.githubusercontent.com/102500164/161230930-bccc40c5-2423-4f2e-bb51-02f87d9f6738.png)
操作步骤：提交重复的项目名称，应该有提示
预期结果：应提示 ，项目名称重复
实际结果：点击提交没有提示

**Comment by LazyEar0** [comment]
未修复

**Comment by LazyEar0** [comment]
resolved
