### ISSUE TITLE
 team--edit item

### ISSUE THREAD

**Issue by wangwenbo33** [masastack/MASA.PM#44]
![image](https://user-images.githubusercontent.com/102500164/161358416-7bf5976e-94bc-452b-9ba2-af1d627a1efb.png)
![image](https://user-images.githubusercontent.com/102500164/161359682-1117f5d1-e3d7-4539-97b9-e58a366f0091.png)
操作步骤：点击编辑项目删除项目，项目里还有应用应提示：“您的项目中还有应用存在”无法删除项目
预期结果：删除项目时项目里有应用应该有提示
实际结果：点击删除并没有提示无法删除

**Comment by LazyEar0** [comment]
resolved
