### ISSUE TITLE
 project- projectID

### ISSUE THREAD

**Issue by wangwenbo33** [masastack/MASA.PM#45]
![image](https://user-images.githubusercontent.com/102500164/161363946-ed2ce640-a378-4897-9f16-6dc808e873a3.png)
![image](https://user-images.githubusercontent.com/102500164/161364023-c107f080-02b3-4dd5-90b9-12d133b5109a.png)

预期结果：设计显示项目ID
实际结果：没有显示项目ID

**Comment by LazyEar0** [comment]
resolved
