### ISSUE TITLE
The new environment

### ISSUE THREAD

**Issue by wangwenbo33** [masastack/MASA.PM#56]
![image](https://user-images.githubusercontent.com/102500164/165685128-4cf9ae87-e2f1-46dd-920b-5ec5198c3921.png)
![企业微信截图_16511244627337](https://user-images.githubusercontent.com/102500164/165685138-602893df-a9af-47b7-bfc9-7633348f71c1.png)

点击新增环境，颜色选择橙色，蓝色，黄色都会报错

**Comment by LazyEar0** [comment]
选择黄色报错
![image](https://user-images.githubusercontent.com/95004531/179676945-19ab7ebb-933c-4a37-b603-332ecfaa7a1c.png)

**Comment by LazyEar0** [comment]
resolved
