### ISSUE TITLE
Editor application

### ISSUE THREAD

**Issue by wangwenbo33** [masastack/MASA.PM#67]
![image](https://user-images.githubusercontent.com/102500164/171099136-7fc30878-574e-4c26-bea0-eff79dd6ea53.png)
![image](https://user-images.githubusercontent.com/102500164/171099361-8ada3494-adde-4016-9be5-5c13ed88875a.png)

已把环境删除，应不显示环境，实际环境还在显示

**Comment by LazyEar0** [comment]
resolved
