### ISSUE TITLE
Initialization,The environment name and description validate Spaces and carriage returns

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.PM#76]
![image](https://user-images.githubusercontent.com/95004531/172984157-6d2b09e3-083a-4853-881c-5685c258f986.png)

初始化，环境名称和环境描述没有进行空格和回车验证；
环境名称不可以输入空格；
环境描述不可以只输入空格或回车

**Comment by codding-y** [comment]
@xie1wei2  environment desctiption should have no input restrictions

**Comment by codding-y** [comment]
产品确认：描述没有限制

**Comment by LazyEar0** [comment]
去掉了初始化页面
