### ISSUE TITLE
Landspace，When adding an environment, you are advised to automatically configure the default value for the associated cluster

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.PM#78]
![image](https://user-images.githubusercontent.com/95004531/172995959-e6875d13-761d-44b9-a27a-5f6a66621027.png)

新增环境时，关联集群建议自动填充默认集群（即初始化时增加的集群）

**Comment by yanzhangpeng** [comment]
#270 Add cluster default value for new environment function

**Comment by masastack-opensource** [comment]
在另一个项目重构
